FillGaps.SoundHub/FillGaps.SoundHub.WebApp/Controllers/ArtistasController.cs
using FillGaps.SoundHub.WebApp.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FillGaps.SoundHub.WebApp.Controllers
{
    [Authorize]
    public class ArtistasController : Controller
    {
        private readonly IApiClientService _apiClientService;

        public ArtistasController(IApiClientService apiClientService)
        {
            _apiClientService = apiClientService;
        }

        public async Task<IActionResult> Index(string termoBusca)
        {
            var viewModel = await _apiClientService.ObterDadosPaginaArtistasAsync(termoBusca);

            ViewData["TermoBuscaAtual"] = termoBusca;

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Favoritar(Guid artistaId)
        {
            await _apiClientService.FavoritarArtistaAsync(artistaId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Desfavoritar(Guid artistaId)
        {
            await _apiClientService.DesfavoritarArtistaAsync(artistaId);
            return RedirectToAction("Index");
        }
    }
}

FillGaps.SoundHub/FillGaps.SoundHub.WebApp/Controllers/DashboardController.cs
using FillGaps.SoundHub.WebApp.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FillGaps.SoundHub.WebApp.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IApiClientService _apiClientService;

        public DashboardController(IApiClientService apiClientService)
        {
            _apiClientService = apiClientService;
        }
        public async Task<IActionResult> IndexAsync()
        {
            ViewData["UserName"] = User.FindFirst(ClaimTypes.Name)?.Value;
            var favoritos = await _apiClientService.ObterMeusFavoritosAsync();
            return View(favoritos);
        }
    }
}

FillGaps.SoundHub/FillGaps.SoundHub.WebApp/Controllers/MusicasController.cs
using FillGaps.SoundHub.WebApp.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FillGaps.SoundHub.WebApp.Controllers
{
    [Authorize]
    public class MusicasController : Controller
    {
        private readonly IApiClientService _apiClientService;

        public MusicasController(IApiClientService apiClientService)
        {
            _apiClientService = apiClientService;
        }

        public async Task<IActionResult> Index(string termoBusca)
        {
            var viewModel = await _apiClientService.ObterDadosPaginaMusicasAsync(termoBusca);

            ViewData["TermoBuscaAtual"] = termoBusca;

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Favoritar(Guid musicaId)
        {
            await _apiClientService.FavoritarMusicaAsync(musicaId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Desfavoritar(Guid musicaId)
        {
            await _apiClientService.DesfavoritarMusicaAsync(musicaId);
            return RedirectToAction("Index");
        }
    }
}

FillGaps.SoundHub/FillGaps.SoundHub.WebApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoundHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FillGaps.SoundHub.WebApp.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="icon" href="~/favicon.svg" type="image/svg+xml">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.svg" alt="SoundHub Logo" width="30" height="30" class="me-2">
                    SoundHub
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Artistas" asp-action="Index">Artistas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Musicas" asp-action="Index">Músicas</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (User.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#">Olá, @User.FindFirst("fullname")?.Value!</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Sair</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Registrar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - SoundHub by FillGaps - <a asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>